blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/jannis793/linkchecker-py/discussions
    about: Start a discussion for broad ideas or usage questions.
